// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Post = require("./Post.js");
var $$Array = require("bs-platform/lib/js/array.js");
var TitleBar = require("./TitleBar.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");

function makePost(author, text) {
  return /* record */[
          /* author */author,
          /* text */text
        ];
}

var posts = /* array */[
  /* record */[
    /* author */"Xin",
    /* text */"The road is endless."
  ],
  /* record */[
    /* author */"Gondar",
    /* text */"You can't fight what you can't see."
  ]
];

function createPostElement(key, post) {
  return ReasonReact.element(String(key), undefined, Post.make(post, /* array */[]));
}

function app(param) {
  return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                  ReasonReact.element(undefined, undefined, TitleBar.make(/* array */[])),
                  ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[$$Array.mapi(createPostElement, posts)]))
                ]));
}

exports.makePost = makePost;
exports.posts = posts;
exports.createPostElement = createPostElement;
exports.app = app;
/* Post Not a pure module */
